---
ansible_user: og6xk9f
group_roles:
  - base
  - workstation
group_packages:
  - awscli2
  - helm
  - k9s
  - kubernetes1.34-client
  - pinentry  # for GnuPG
  - restic
  - sqlite  # for ZSH history
  - zsh
group_py_modules: []
